#!/usr/bin/python
import smtplib

# Use this method instead: https://stackoverflow.com/questions/73781/sending-mail-via-sendmail-from-python

from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart

import time

import os
os.chdir( "/opt/speedtest" )

msg = MIMEMultipart()

msg['Subject'] = "Hastighetsrapport [" + time.strftime("%Y-%m-%dT%H:%M:%S") + "]"
msg['From'] = "daniel@armyr.se"
msg['To'] = "postmaster@armyr.se"

text = MIMEText("Hastighetsrapport")
msg.attach( text )

img = open( "image.png", 'rb').read()
image = MIMEImage( img, name="image.png" )
msg.attach( image )

s = smtplib.SMTP('smtp.bredband.net')
s.set_debuglevel(False)
s.sendmail( 'daniel@armyr.se', 'postmaster@armyr.se', msg.as_string() )
s.quit
