#!/usr/bin/python

import speedtest
import logging
import os

def doSpeedtestAPI():
	servers = []
	s = speedtest.Speedtest()
	s.get_servers(servers)
	s.get_best_server()
	s.download()
	s.upload()

	results = s.results.dict()

	return results


#-----------------
# Main program
#-----------------

# Configure the logger
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)
logger.info ("Program starting")

# Change CWD to where our files are stored
os.chdir( "/opt/speedtest/" ) 
logger.info ( "Program running in folder: %s", os.getcwd() )

# Run the core of the program
result = doSpeedtestAPI()
logger.debug( "Data received: %s", result )

logger.info ( "Program done" )
