#!/usr/bin/python

from subprocess import Popen, PIPE
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart

import time

import os
os.chdir( "/opt/speedtest" )

msg = MIMEMultipart()

msg['Subject'] = "Hastighetsrapport [" + time.strftime("%Y-%m-%dT%H:%M:%S") + "]"
msg['From'] = "daniel@armyr.se"
msg['To'] = "postmaster@armyr.se"

text = MIMEText("Hastighetsrapport")
msg.attach( text )

img = open( "image.png", 'rb').read()
image = MIMEImage( img, name="image.png" )
msg.attach( image )

## This method uses sendmail or equivalent rather than connect directly to the smtp server
p = Popen( ["/usr/sbin/sendmail", "-t", "-oi"], stdin=PIPE )
p.communicate( msg.as_string() )

